### ISSUE TITLE
update_ssh_config: new entries should be inserted before "host *" section

### ISSUE THREAD

**Issue by mwilck** [mcgrof/kdevops#3]
`update_ssh_config.py` simply appends the entries for vagrant hosts to the end of the `.ssh/config` file. But that may not yield desired results. From ssh_config(5):

> Since the first obtained value for each parameter is used, more host-specific declarations should be given near the beginning of the file, and general defaults at the end.

Thus if the user has a global defaults section (`Host *`), settings from that section will override those from the vagrant-generated section. For example, I have the following global section:

```
Host *
    Compression yes
    IdentityFile  ~/.ssh/id_ed25519,~/.ssh/id_ecdsa
    PubkeyAcceptedKeyTypes ssh-ed25519
    HostKeyAlgorithms ssh-ed25519
```

This causes the public-key login to the vagrant box to fail with the cryptic error message `sign_and_send_pubkey: no mutual signature supported` (falling back to password auth). In order to fix this, I had to add a line `PubkeyAcceptedKeyTypes rsa-sha2-512` in the kdevops record, and move the entire record before the global section.

(I made the `PubkeyAcceptedKeyTypes` setting to avoid silently using old DSA keys I used to have around. You may call that setting of mine over-paranoid. Reporting this nonetheless. The ordering of entries may matter in other situations, too.)

Additional remark, it would be helpful to list the IP address of the vagrant VM on the "Host" line, too. Without that, the entry matches only if the host name (e.g. `kdevops`) is used, and not with the IP address. `vagrant ssh` uses the IP address and thus, may fail where `ssh kdevops` succeeds.

I know I should send patches rather than whine here. I would but I have no time in the short run.
Thanks for this project, it's awesome in general.

**Comment by mcgrof** [comment]
> `update_ssh_config.py` simply appends the entries for vagrant hosts to the end of the `.ssh/config` file. But that may not yield desired results. From ssh_config(5):
> 
> > Since the first obtained value for each parameter is used, more host-specific declarations should be given near the beginning of the file, and general defaults at the end.
> 
> Thus if the user has a global defaults section (`Host *`), settings from that section will override those from the vagrant-generated section. For example, I have the following global section:
> 
> ```
> Host *
>     Compression yes
>     IdentityFile  ~/.ssh/id_ed25519,~/.ssh/id_ecdsa
>     PubkeyAcceptedKeyTypes ssh-ed25519
>     HostKeyAlgorithms ssh-ed25519
> ```
> 
> This causes the public-key login to the vagrant box to fail with the cryptic error message `sign_and_send_pubkey: no mutual signature supported` (falling back to password auth). In order to fix this, I had to add a line `PubkeyAcceptedKeyTypes rsa-sha2-512` in the kdevops record, and move the entire record before the global section.
> 
> (I made the `PubkeyAcceptedKeyTypes` setting to avoid silently using old DSA keys I used to have around. You may call that setting of mine over-paranoid. Reporting this nonetheless. The ordering of entries may matter in other situations, too.)

Thanks for the report. This is now fixed on kdevops v4.1.0-rc10.

> Additional remark, it would be helpful to list the IP address of the vagrant VM on the "Host" line, too. Without that, the entry matches only if the host name (e.g. `kdevops`) is used, and not with the IP address. `vagrant ssh` uses the IP address and thus, may fail where `ssh kdevops` succeeds.

I do not understand what you meant to say here. Perhaps you provide an example, or, since you can see how I changed this, you might be inspired for a patch / test.

**Comment by mwilck** [comment]
> I do not understand what you meant to say here. Perhaps you provide an example, or, since you can see how I changed this, you might be inspired for a patch / test.

When I tried to debug what went wrong with the issue reported here, I experimented with calling vagrant directly, using "vagrant ssh". In my testing at least, this would internally call `ssh $IP_ADDRESS_of_VM` rather than `ssh $HOSTNAME_of_VM`, and thus the `Host` entry you generated wouldn't match. When I do manual maintenance of `~/.ssh/config`, I usually add both hostname _and_ IP address on the `Host` line, like this:

    Host nashorn.local 192.168.1.168
        User admin
        HostKeyAlgorithms ssh-rsa

Hope that clarifies it. It's a minor issue anyway.

**Comment by mcgrof** [comment]
> Host nashorn.local 192.168.1.168
>     User admin
>     HostKeyAlgorithms ssh-rsa
> ```

Ah, is this a new feature? Or has this *always* been supported. Granted, kdevops aims to be used on rolling distros, but it would be nice to know if this has been supported for eons.

**Comment by mwilck** [comment]
You mean, several entries on a host line? I think it's been supported for a while. I've been doing it at least for 4y now (having been on TW all the time, though).

**Comment by mcgrof** [comment]
> You mean, several entries on a host line? I think it's been supported for a while. I've been doing it at least for 4y now (having been on TW all the time, though).

OK I've added support for this, its in v4.1.0-rc12
